name: First Cron Job
on:
  push:
    branches:
      - main
      - develop
  schedule:
    #        m h d m dow
    - cron: "*/1 * * * *"
  workflow_dispatch:
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - name: generate label
        id: release_tag
        run: |
          echo "today=$(date +'%Y.%m.%d.%H.%M.%S')" >> $GITHUB_OUTPUT
      - name: curl date
        run: curl -O https://www.nict.go.jp/JST/JST5.html
      - name: debug
        run: echo ${{ steps.release_tag.outputs.today }}
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ steps.release_tag.outputs.today }}
          tag_name: ${{ steps.release_tag.outputs.today }}
          files: |
            JST5.html

#name: Scheduled build
#
#on:
#  schedule:
#    # 月曜日の 11:00 (JST) に処理を実行する。
#    # UTC の 02:00 は JST だと 11:00 。
#    - cron: '* * * * *'

#permissions:
#  contents: write

#jobs:
#  build:
#    name: build
#   runs-on: ubuntu-latest
#    steps:
#      - name: curl
#        run: curl https://www.nict.go.jp/JST/JST5.html
#      - name: generate label
#        id: release_tag
#        run: |
#          today=$(date +'%Y.%m.%d.%H.%M.%S')
#          echo $today
#      - name: Create Release
#        run: |
#          gh release create [ta --generate-notes [attachment-file]
#        env:
#          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
